services:
  web:
    image: zauberzeug/nicegui:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - PUID=1000 # change this to your user id
      - PGID=1000 # change this to your group id
    volumes:
      - ./web/:/app/
  api:
    build: api
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - ./api/:/app/
    ports:
      - 8081:8000
